name: Deploy to K8s

on:
  pull_request:
    types: ['closed']

permissions:
  contents: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: trevorcarlson24/trevor-cicd-practice    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Get commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV        

      - name: Setup Git User
        uses: fregante/setup-git-user@v1

      - name: Install python bump2version
        shell: bash
        run: pip install -U bump2version

      - name: BumpVersion
        id: bumpversion
        run: |
            cat VERSION
            bump2version --current-version $(cat VERSION | sed -e 's/.*://') patch --allow-dirty
            echo "NEW_VERSION=$(cat VERSION | sed -e 's/.*://')" >> $GITHUB_ENV
            NEW_VERSION=$(cat VERSION | sed -e 's/.*://')
            echo $NEW_VERSION  

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Tag and Push Docker image to DockerHub
        run: |
          TAG_NAME="pr-${COMMIT_HASH}"
          docker build -t $IMAGE_NAME:$TAG_NAME .
          docker tag $IMAGE_NAME:$TAG_NAME $IMAGE_NAME:$NEW_VERSION
          docker push $IMAGE_NAME:$NEW_VERSION

      - name: Commit version
        uses: actions-js/push@master
        with:
          message: 'Update app to to $NEW_VERSION'
          force: true
          github_token: ${{ secrets.MY_PAT }}
