name: Docker PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: trevorcarlson24/trevor-cicd-practice

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          TAG_NAME="pr-${COMMIT_HASH}"
          docker build -t $IMAGE_NAME:$TAG_NAME .

      - name: Push Docker image to DockerHub
        run: |
          TAG_NAME="pr-${COMMIT_HASH}"
          docker push $IMAGE_NAME:$TAG_NAME
      
      - name: Install Docker Scout
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          docker scout --help || echo "Docker Scout is installed."
      
      - name: Run Docker Scout Quickview
        id: scout
        run: |
          TAG_NAME="pr-${COMMIT_HASH}"
          docker scout quickview $IMAGE_NAME:$TAG_NAME > scout_report.txt
          cat scout_report.txt

      - name: Post Docker Scout output as PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: scout_report.txt
